---
title: "Spatial-Data"
author: "Kennalyn Peterson"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
source("setup.R")
library(tigris, elevatr)
```

```{r}
# Import Colorado counties 
counties <- counties(state = "CO")
```

```{r}
# Imports Roads for Larimer County
roads <- roads(state = "CO", county = "Larimer")
```

```{r}
# Set tmap mode to Interactive
tmap_mode("view")
```

```{r}
#Using qtm
qtm(counties)+
  qtm(roads)

#Using tm_shape
tm_shape(counties)+
  tm_polygons()+
tm_shape(roads)+
  tm_lines()
```

```{r}
#Point Data
poudre_points <- data.frame(name = c("Mishawaka", "Rustic", "Blue Lake Trailhead"),
                            long = c(-105.35634, -105.58159, -105.85563),
                            lat = c(40.68752, 40.69687, 40.57960))
```

```{r}
# Convery points to spatial data
poudre_points_sf <- st_as_sf(poudre_points, coords = c("long", "lat"), crs = 4326)

```

```{r}
#raster data
elevation <- get_elev_raster(counties, z = 7)

qtm(elevation)

tm_shape(elevation)+
  tm_raster(style = "cont", title = "Elevation (m)")
```

```{r}
# The terra package
elevation <- rast(elevation)

names(elevation) <- "Elevation"

```

```{r}
#Check projection
st_crs(elevation)

crs(counties) == crs(elevation)
```

```{r}
#Project elevation layer
elevation_prj <- terra::project(elevation, counties)
```

```{r}
# Crop to counties extent
elevation_crop <- crop(elevation, ext(counties))

qtm(elevation_crop)
```

```{r}
#Save sf/vector data
write_sf(counties, "data/counties.shp")
```

```{r}
# Save raster data
writeRaster(elevation_crop, "data/elevation.tif")
```

```{r}
#Save .Rdata
save (counties, roads, file = "data/spatial_objects.RData")
```

```{r}
# 4 Exercises 1
counties_filtered <- filter(counties, NAME == "Larimer" | NAME == "Denver" | NAME == "Pueblo")
qtm(counties_filtered)
```

```{r}
# 4 Exercise 2
counties
qtm(counties, fill = "ALAND")
qtm(counties, fill = "AWATER")
```
